apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: compose-post-service
  name: compose-post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compose-post-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: compose-post-service
        death-star-project: social-network
        app-name: compose-post-service
        injection: able
    spec:
      containers:
        - command:
            - ComposePostService
          image: yg397/social-network-microservices:latest
          name: compose-post-service
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: compose-post-service-hostpath0
            - mountPath: /keys
              name: compose-post-service-hostpath1
      hostname: compose-post-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/lizytalk/Projects/DeathStarBench/socialNetwork/config
          name: compose-post-service-hostpath0
        - hostPath:
            path: /Users/lizytalk/Projects/DeathStarBench/socialNetwork/keys
          name: compose-post-service-hostpath1
status: {}
