apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-redis
  name: social-graph-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: social-graph-redis
        death-star-project: social-network
        app-name: compose-post-service
        injection: able
    spec:
      containers:
        - args:
            - /social-network-microservices/config/redis.conf
          image: redis
          name: social-graph-redis
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: social-graph-redis-hostpath0
            - mountPath: /keys
              name: social-graph-redis-hostpath1
      hostname: social-graph-redis
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/lizytalk/Projects/DeathStarBench/socialNetwork/config
          name: social-graph-redis-hostpath0
        - hostPath:
            path: /Users/lizytalk/Projects/DeathStarBench/socialNetwork/keys
          name: social-graph-redis-hostpath1
status: {}
