apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: user-memcached
  name: user-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: user-memcached
        death-star-project: social-network
        app-name: compose-post-service
        injection: able
    spec:
      containers:
        - image: memcached
          name: user-memcached
          resources: {}
      hostname: user-memcached
      restartPolicy: Always
status: {}
