---
apiVersion: v1
kind: Service
metadata:
  name: movie-id-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: movie-id-service
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: media-microsvc
    app-name: movie-id-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-id-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: movie-id-service
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: movie-id-service
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: movie-id-service
        injection: able
      name: movie-id-service
    spec:
      containers:
      - name: movie-id-service
        image: docker.peidan.me/lizytalk/media-microservices
        command: ["MovieIdService"]
        volumeMounts:
        - mountPath: /media-microservices/config/jaeger-config.yml
          name: jaeger-config-yml
        volumeMounts:
        - mountPath: /media-microservices/config/service-config.json
          name: service-config-json
        livenessProbe:
          exec:
            command:
            - exit 1
          failureThreshold: 1
          initialDelaySeconds: 86400
          periodSeconds: 86400
      restartPolicy: Always
      volumes:
      - name: jaeger-config-yml
        hostPath:
          path: /mnt/mfs/DeathStarBench/mediaMicroservices/config/jaeger-config.yml
          type: File
      - name: service-config-json
        hostPath:
          path: /mnt/mfs/DeathStarBench/mediaMicroservices/config/service-config.json
          type: File
