---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: rating-service
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: media-microsvc
    app-name: rating-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: rating-service
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: rating-service
        injection: able
      name: rating-service
    spec:
      containers:
      - name: rating-service
        image: docker.peidan.me/lizytalk/media-microservices
        command: ["RatingService"]
        volumeMounts:
        - mountPath: /media-microservices/config/jaeger-config.yml
          name: jaeger-config-yml
        volumeMounts:
        - mountPath: /media-microservices/config/service-config.json
          name: service-config-json
      restartPolicy: Always
      volumes:
      - name: jaeger-config-yml
        hostPath:
          path: /mnt/mfs/DeathStarBench/mediaMicroservices/config/jaeger-config.yml
          type: File
      - name: service-config-json
        hostPath:
          path: /mnt/mfs/DeathStarBench/mediaMicroservices/config/service-config.json
          type: File
