apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: es-storage
  hostPath:
    path: /mnt/mfs/DeathStarBench/ES-DATA
    type: Directory
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es
  namespace: social-network
spec:
  version: 7.12.1
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: es-storage
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kbn
  namespace: social-network
spec:
  version: 7.12.1
  count: 1
  elasticsearchRef:
    name: es
---
apiVersion: v1
kind: Service
metadata:
  name: es-proxy
  namespace: social-network
spec:
  ports:
  - port: 9200
    nodePort: 30083
    targetPort: 9200
    protocol: TCP
  type: NodePort
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: es