---
apiVersion: v1
kind: Service
metadata:
  name: home-timeline-service
  labels:
    death-star-project: social-network
    app-name: home-timeline-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app-name: home-timeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline-service
  labels:
    death-star-project: social-network
    app-name: home-timeline-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: home-timeline-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: home-timeline-service
        injection: able
      name: home-timeline-service
    spec:
      containers:
      - name: home-timeline-service
        image: yg397/social-network-microservices:latest
        command: ["HomeTimelineService"]
        volumeMounts:
        - mountPath: /social-network-microservices/config
          name: config
        - mountPath: /keys
          name: keys
      restartPolicy: Always
      volumes:
      - name: config
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/config
          type: Directory
      - name: keys
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/keys
          type: Directory
