---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-out
  labels:
    death-star-project: social-network
    app-name: jaeger
  namespace: social-network
spec:
  type: NodePort
  ports:
  - port: 16686
  selector:
    death-star-project: social-network
    app-name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    death-star-project: social-network
    app-name: jaeger
  namespace: social-network
spec:
  ports:
  - port: 5775
    name: udp1
    protocol: UDP
  - port: 5778
    name: tcp1
  - port: 6831
    name: udp2
    protocol: UDP
  - port: 6832
    name: udp3
    protocol: UDP
  - port: 14250
    name: tcp2
  - port: 14268
    name: tcp3
  - port: 16687
    name: admin-http
  - port: 14269
    name: monitor
  selector:
    death-star-project: social-network
    app-name: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    death-star-project: social-network
    app-name: jaeger
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: jaeger
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: jaeger
      name: jaeger
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "16686"
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://es-es-http:9200"
        - name: ES_USERNAME
          value: "elastic"
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es-es-elastic-user
              key: elastic
      restartPolicy: Always
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sn-tracing
  namespace: social-network
spec:
  endpoints:
  - port: monitor
  selector:
    matchLabels:
     app-name: jaeger
