apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: media-service
  name: media-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: media-service
    spec:
      containers:
        - command:
            - MediaService
          image: yg397/social-network-microservices:latest
          name: media-service
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: media-service-hostpath0
            - mountPath: /keys
              name: media-service-hostpath1
      hostname: media-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/lizytalk/Projects/DeathStarBench/socialNetwork/config
          name: media-service-hostpath0
        - hostPath:
            path: /Users/lizytalk/Projects/DeathStarBench/socialNetwork/keys
          name: media-service-hostpath1
status: {}
