---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app-name: social-graph-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app-name: social-graph-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app-name: social-graph-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: social-graph-redis
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: social-graph-redis
        injection: able
      name: social-graph-redis
    spec:
      containers:
      - name: social-graph-redis
        image: redis
        volumeMounts:
        - mountPath: /social-network-microservices/config
          name: config
        - mountPath: /keys
          name: keys
        command: /social-network-microservices/config/redis.conf
      restartPolicy: Always
      volumes:
      - name: config
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/config
          type: Directory
      - name: keys
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/keys
          type: Directory
