---
apiVersion: v1
kind: Service
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app-name: text-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app-name: text-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app-name: text-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: text-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: text-service
      name: text-service
    spec:
      containers:
      - name: text-service
        image: docker.peidan.me/lizytalk/social-network-microservices
        command: ["TextService"]
        volumeMounts:
        - mountPath: /social-network-microservices/config/jaeger-config.yml
          name: jaeger-config-yml
        volumeMounts:
        - mountPath: /social-network-microservices/config/service-config.json
          name: service-config-json
      restartPolicy: Always
      volumes:
      - name: jaeger-config-yml
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/config/jaeger-config.yml
          type: File
      - name: service-config-json
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/config/service-config.json
          type: File
