---
apiVersion: v1
kind: Service
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app-name: text-service

spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app-name: text-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app-name: text-service

spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: text-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: text-service
      name: text-service
    spec:
      containers:
      - name: text-service
        image: docker.peidan.me/lizytalk/social-network-microservices
        command: ["TextService"]
      restartPolicy: Always
