apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: unique-id-service
  name: unique-id-service
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: unique-id-service
status:
  loadBalancer: {}
