---
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-mongodb
  labels:
    death-star-project: social-network
    app-name: url-shorten-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app-name: url-shorten-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shorten-mongodb
  labels:
    death-star-project: social-network
    app-name: url-shorten-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: url-shorten-mongodb
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: url-shorten-mongodb
        injection: able
      name: url-shorten-mongodb
    spec:
      containers:
      - name: url-shorten-mongodb
        image: mongo
        volumeMounts:
        - mountPath: /social-network-microservices/config
          name: config
        - mountPath: /keys
          name: keys
        args: ["--config", "/social-network-microservices/config/mongod.conf"]
      restartPolicy: Always
      volumes:
      - name: config
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/config
          type: Directory
      - name: keys
        hostPath:
          path: /mnt/mfs/DeathStarBench/socialNetwork/keys
          type: Directory
