apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: url-shorten-memcached
  name: url-shorten-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: url-shorten-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: url-shorten-memcached
    spec:
      containers:
        - image: memcached
          name: url-shorten-memcached
          ports:
            - containerPort: 11211
          resources: {}
      hostname: url-shorten-memcached
      restartPolicy: Always
status: {}
